package formatter

import (
	"fmt"
	"strings"
	"time"

	"github.com/lusoris/redflag/internal/scanner"
)

// Post holds the Reddit post title and body.
type Post struct {
	Title string
	Body  string
}

// FormatPost creates a Reddit-flavored markdown post for new vulnerabilities.
func FormatPost(appName, image string, vulns []scanner.Vulnerability) *Post {
	critCount := 0
	highCount := 0
	for _, v := range vulns {
		switch v.Severity {
		case "CRITICAL":
			critCount++
		case "HIGH":
			highCount++
		}
	}

	title := formatTitle(appName, critCount, highCount)

	var b strings.Builder

	b.WriteString(fmt.Sprintf("# 🚩 Security Alert: %s\n\n", appName))
	b.WriteString(fmt.Sprintf("**Image:** `%s`\n\n", image))
	b.WriteString(fmt.Sprintf("**Scan Date:** %s\n\n", time.Now().UTC().Format("2006-01-02")))
	b.WriteString(fmt.Sprintf("**New Vulnerabilities Found:** %d (%d Critical, %d High)\n\n", len(vulns), critCount, highCount))

	b.WriteString("---\n\n")

	// Vulnerability table
	b.WriteString("| CVE | Severity | Package | Installed | Fixed | Details |\n")
	b.WriteString("|-----|----------|---------|-----------|-------|---------|\n")

	for _, v := range vulns {
		fixed := v.FixedVersion
		if fixed == "" {
			fixed = "No fix"
		}

		nvdURL := fmt.Sprintf("https://nvd.nist.gov/vuln/detail/%s", v.VulnerabilityID)
		if v.PrimaryURL != "" {
			nvdURL = v.PrimaryURL
		}

		title := v.Title
		if len(title) > 60 {
			title = title[:57] + "..."
		}

		b.WriteString(fmt.Sprintf("| [%s](%s) | **%s** | %s | %s | %s | %s |\n",
			v.VulnerabilityID, nvdURL, v.Severity, v.PkgName,
			v.InstalledVersion, fixed, title))
	}

	b.WriteString("\n---\n\n")
	b.WriteString("*This report was automatically generated by [RedFlag](https://github.com/lusoris/RedFlag) — ")
	b.WriteString("an automated Trivy CVE scanner for homelab container images.*\n")

	return &Post{
		Title: title,
		Body:  b.String(),
	}
}

func formatTitle(appName string, critical, high int) string {
	parts := []string{}
	if critical > 0 {
		parts = append(parts, fmt.Sprintf("%d Critical", critical))
	}
	if high > 0 {
		parts = append(parts, fmt.Sprintf("%d High", high))
	}

	severity := strings.Join(parts, ", ")
	return fmt.Sprintf("[Security] %s — %s vulnerabilit%s found",
		appName, severity, pluralSuffix(critical+high))
}

func pluralSuffix(count int) string {
	if count == 1 {
		return "y"
	}
	return "ies"
}
